{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d8ead6f8",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:11:48.377204Z",
     "start_time": "2022-01-14T16:11:25.219230Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/3903838457.py:10: UserWarning: \n",
      "The dash_core_components package is deprecated. Please replace\n",
      "`import dash_core_components as dcc` with `from dash import dcc`\n",
      "  import dash_core_components as dcc\n",
      "/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/3903838457.py:11: UserWarning: \n",
      "The dash_html_components package is deprecated. Please replace\n",
      "`import dash_html_components as html` with `from dash import html`\n",
      "  import dash_html_components as html\n"
     ]
    }
   ],
   "source": [
    "# importing all necessary libs\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from urllib.request import urlopen\n",
    "import json\n",
    "import plotly.express as px\n",
    "import plotly.graph_objs as go\n",
    "import dash\n",
    "import os\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from plotly.subplots import make_subplots\n",
    "import py7zr\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "import scipy.stats\n",
    "from scipy.stats import expon\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "11d1f560",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:14:02.223376Z",
     "start_time": "2022-01-14T16:12:19.448900Z"
    }
   },
   "outputs": [],
   "source": [
    "curr_dir = os.getcwd()\n",
    "parent_dir = os.path.dirname(curr_dir)\n",
    "\n",
    "# Data reading\n",
    "with py7zr.SevenZipFile(parent_dir + '/data/globalterrorismdb_0221dist.7z') as z:\n",
    "    # open the csv file in the dataset\n",
    "    targetPath = os.path.expanduser(\"~/Desktop/GT Dataset\")\n",
    "    z.extract(path = targetPath)\n",
    "    df = pd.read_excel(targetPath + '/globalterrorismdb_0221dist.xlsx')\n",
    "    \n",
    "# We filtered out doubted attacks to be able to have exact attacks\n",
    "df = df[df['doubtterr'] != 1]\n",
    "\n",
    "_df = df[['eventid','iyear','imonth','iday','country','country_txt',\n",
    "         'region','region_txt', 'provstate', 'city','latitude','longitude',\n",
    "         'gname','nkill', 'nwound']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "df8a63f4",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:21:44.767223Z",
     "start_time": "2022-01-14T16:21:44.375925Z"
    }
   },
   "outputs": [],
   "source": [
    "# Geojson for polygons of map\n",
    "with urlopen('https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json') as response:\n",
    "    countries = json.load(response)\n",
    "                          \n",
    "countries_df = pd.json_normalize(countries,  record_path =['features'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "064d2461",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:21:46.518429Z",
     "start_time": "2022-01-14T16:21:45.485712Z"
    }
   },
   "outputs": [],
   "source": [
    "# Updating the countries to be able to merge -- TODO: !!!!\n",
    "_df.loc[_df['country_txt'] == 'Bahamas','country_txt']  = 'The Bahamas'\n",
    "_df.loc[_df['country_txt'] == 'United States','country_txt'] = 'United States of America'\n",
    "_df.loc[_df['country_txt'] == 'Czechoslovakia','country_txt'] = 'Czech Republic'\n",
    "_df.loc[_df['country_txt'] == 'East Germany (GDR)','country_txt']  = 'Germany'\n",
    "_df.loc[_df['country_txt'] == 'West Germany (FRG)','country_txt']  = 'Germany'\n",
    "\n",
    "_df.loc[_df['country_txt'] == 'West Bank and Gaza Strip','country_txt'] = 'West Bank'\n",
    "_df.loc[_df['country_txt'] == 'South Vietnam','country_txt'] = 'Vietnam'\n",
    "_df.loc[_df['country_txt'] == 'North Yemen','country_txt'] = 'Yemen'\n",
    "_df.loc[_df['country_txt'] == 'South Yemen','country_txt'] = 'Yemen'\n",
    "#_df.loc[_df['country_txt'] == 'Andorra','country_txt'] = 'Spain'\n",
    "_df.loc[_df['country_txt'] == 'Bahrain','country_txt'] = 'Iran'\n",
    "_df.loc[_df['country_txt'] == 'Tanzania','country_txt'] = 'United Republic of Tanzania'\n",
    "\n",
    "for ind in _df.index:\n",
    "    if _df.loc[ind,'country_txt'] in ['Soviet Union', 'Yugoslavia']:\n",
    "        _df.loc[ind,'country_txt'] = _df.loc[ind,'provstate']\n",
    "\n",
    "\n",
    "_df.loc[_df['country_txt'] == 'Bosnia-Herzegovina','country_txt'] = 'Bosnia and Herzegovina'\n",
    "_df.loc[_df['country_txt'].isin(['Central Serbia','Serbia','Serbia-Montenegro',\n",
    "                                 'Republika Srpska','Belgrade','Kosovo and Metohija']),'country_txt'] = 'Republic of Serbia'  \n",
    "_df.loc[_df['country_txt'] == 'Yugoslavia','country_txt'] = 'Republic of Serbia'\n",
    "_df.loc[_df['country_txt'] == 'International','country_txt'] = 'United Arab Emirates'\n",
    "_df.loc[_df['country_txt'] == 'Hong Kong','country_txt'] = 'China' \n",
    "_df.loc[_df['country_txt'] == 'Kygyzstan','country_txt'] = 'Kyrgyzstan'\n",
    "_df.loc[_df['country_txt'] == 'Maldives','country_txt'] = 'India'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "dde2beba",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:21:47.526587Z",
     "start_time": "2022-01-14T16:21:47.411322Z"
    }
   },
   "outputs": [],
   "source": [
    "# Merging locations and main df\n",
    "df_merged = pd.merge(_df, countries_df , left_on = 'country_txt', right_on = 'properties.name', how = 'left' )\n",
    "\n",
    "# Determine ig organized or unorganized\n",
    "df_merged['isOrganized'] = ['unorganized' if i == 'Unknown' else 'organized' for i in df_merged['gname']]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "215a949f",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:21:47.770178Z",
     "start_time": "2022-01-14T16:21:47.767570Z"
    }
   },
   "outputs": [],
   "source": [
    "def grouped_weighted_avg(values, weights, by):\n",
    "    return (values * weights).groupby(by).sum()  / weights.groupby(by).sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "9b2408bb",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-01-14T16:21:48.189879Z",
     "start_time": "2022-01-14T16:21:48.136497Z"
    }
   },
   "outputs": [],
   "source": [
    "weights =  np.linspace(expon.ppf(0.01), expon.ppf(0.99), len(df_merged.iyear.unique()))\n",
    "weights = weights/ np.sum(weights)\n",
    "\n",
    "years = df_merged.iyear.unique()\n",
    "weighted_years = pd.DataFrame({'years': years, 'weights': weights})\n",
    "\n",
    "_df = pd.merge(df_merged, weighted_years, left_on = 'iyear', right_on = 'years', how = 'inner')\n",
    "_df['total_kills_injured'] = _df['nkill'] + _df['nwound']\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d9ff8c49",
   "metadata": {
    "ExecuteTime": {
     "start_time": "2022-01-16T10:49:35.484Z"
    },
    "code_folding": [
     1,
     163,
     183
    ]
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:37] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_favicon.ico?v=2.0.0 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"GET /_favicon.ico?v=2.0.0 HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 175, in update_incidents\n",
      "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 262, in line\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/plotly/express/_core.py\", line 1306, in build_dataframe\n",
      "    args[\"data_frame\"] = pd.DataFrame(args[\"data_frame\"])\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py\", line 730, in __init__\n",
      "    raise ValueError(\"DataFrame constructor not properly called!\")\n",
      "ValueError: DataFrame constructor not properly called!\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/opt/homebrew/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/26/9mt94nq12r58hxyl1vm__cs00000gn/T/ipykernel_29997/2841647266.py\", line 200, in update_fatalities\n",
      "    go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
      "TypeError: string indices must be integers\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [16/Jan/2022 11:49:38] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [16/Jan/2022 11:49:39] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "# We need safety index calculation before groupby\n",
    "def update_map():\n",
    "    df_map = _df.groupby(by=['country','country_txt','id', 'iyear']).agg({\n",
    "                                                                'nkill': np.sum,\n",
    "                                                                'nwound': np.sum,\n",
    "                                                                'total_kills_injured':np.sum,\n",
    "                                                                'eventid': 'count', \n",
    "                                                                'weights': np.mean}).reset_index()  #weights same for same years\n",
    "    \n",
    "    calculated_indexes =  pd.DataFrame(grouped_weighted_avg(values=df_map.eventid, \n",
    "                                                    weights=df_map.weights, \n",
    "                                                    by=df_map.id)).reset_index().rename(columns={0: 'calculated_index'})\n",
    "    \n",
    "    df_map = df_map.groupby(by=['country','country_txt','id']).agg({\n",
    "                                                                'nkill': np.sum,\n",
    "                                                                'nwound': np.sum,\n",
    "                                                                'total_kills_injured':np.sum}).reset_index()\n",
    "    \n",
    "    df_map = pd.merge(df_map, calculated_indexes, on = 'id', how = 'left')\n",
    "\n",
    "    df_map['hover_text'] = 'Country: ' + df_map[\"country_txt\"].astype(str) + \"<br>\" + 'Unsafety Index: ' + df_map['calculated_index'].round(decimals= 2).astype(str) + '<br>'+'# of Killed and Wounded People: ' +  df_map['total_kills_injured'].astype(str)+ '<br>'+'# of Killed People: '+  df_map['nkill'].astype(str)+ '<br>'+ '# of Wounded People: '+  df_map['nwound'].astype(str)\n",
    "    \n",
    "    trace = go.Choropleth(locations=df_map['id'],\n",
    "                          z=df_map['calculated_index'],\n",
    "                          text=df_map['hover_text'], \n",
    "                          hoverinfo='text' ,\n",
    "                          colorscale=\"rdylgn\",\n",
    "                          reversescale = True,\n",
    "                          marker={'line': {'color': 'rgb(180,180,180)','width': 0.5}},\n",
    "                          colorbar={\"thickness\": 20,\"len\": 0.7, \"x\": 0.9, \"y\": 0.7,\n",
    "                                   'title': {\"text\": 'Safety Index', \"side\": \"bottom\"},\n",
    "                                 }\n",
    "                         )   \n",
    "    return {\"data\": [trace],\n",
    "            \"layout\": go.Layout(height=800, width= 1200 ,\n",
    "                                geo={'showframe': False,\n",
    "                                     'showcoastlines': False,\n",
    "                                     'projection': {'type': \"miller\"}})}\n",
    "\n",
    "\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "app.title = 'Dashboard'\n",
    "\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.Div([html.H1(\"Global Terrorism Dashboard\")],\n",
    "                 style={'textAlign': \"center\", \"padding-bottom\": \"30\"}, \n",
    "                 className=\"six-column\"),\n",
    "    html.Div([dcc.Graph(id=\"world-map\", \n",
    "                       style = {'textAlign': \"center\"}, \n",
    "                       figure = update_map(), className=\"twelve columns\"), \n",
    "              html.A('Source: Global Terrorism Database(GTD)',href = 'https://www.start.umd.edu/gtd/', \n",
    "                      style={'fontStyle': \"italic\", 'color': '#273746'})]), \n",
    "    html.Div([html.H2('First 15 Countries with Most Organized and Unorganized Attacks'),\n",
    "              dcc.Graph(id=\"horizontal-bar\")], \n",
    "             className=\"twelve columns\"),\n",
    "    html.H2(id = 'country-name',  children=[\"init\"] , \n",
    "            style={'textAlign': \"center\", \"padding-bottom\": \"30\"} ),\n",
    "    html.Div(dcc.Graph(id=\"incidents\"),  id = 'incident-box', \n",
    "             style = {'visibility': 'hidden'}, className=\"five columns\"),\n",
    "    html.Div(dcc.Graph(id=\"fatalities\"),  id = 'fatalities-box', \n",
    "             style = {'visibility': 'hidden'}, className=\"five columns\"),\n",
    "    \n",
    "])\n",
    "\n",
    "\n",
    "##### Figure Updates with CallBacks ##### \n",
    "@app.callback(\n",
    "    dash.dependencies.Output('country-name', 'children'),\n",
    "    [dash.dependencies.Input('world-map', 'clickData')])\n",
    "def update_title(clickData):\n",
    "    text = ''\n",
    "    if clickData is not None:\n",
    "        selected_country = clickData['points'][0]['location']\n",
    "        text = str(selected_country)  \n",
    "    return text\n",
    "\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('horizontal-bar', 'figure'),\n",
    "    [dash.dependencies.Input('world-map', 'clickData')])\n",
    "def update_horizontal_bar(clickData):\n",
    "    def get_data(year):\n",
    "        df_h = df_merged[df_merged['iyear'] == year].groupby(by=['country','country_txt',\n",
    "                                       'id', 'isOrganized']).agg({'eventid':'count'}).unstack(fill_value=0).stack().sort_values(by='country').reset_index()\n",
    "        df_x = df_h.pivot_table(index=['country','country_txt'], columns='isOrganized')\n",
    "        countries = df_h.drop_duplicates(subset=['country','country_txt']).reset_index()[['country','country_txt']]\n",
    "        countries['organized'] = df_x['eventid']['organized'].reset_index()['organized']\n",
    "        countries['unorganized'] = df_x['eventid']['unorganized'].reset_index()['unorganized']\n",
    "        countries['Total'] = countries['organized'] +countries['unorganized']\n",
    "        countries = countries.sort_values(by='Total', ascending= False)[0:15]\n",
    "\n",
    "        return countries\n",
    "\n",
    "    fig = go.Figure()\n",
    "    years = df_merged['iyear'].unique()\n",
    "\n",
    "    for step in years:\n",
    "        countries = get_data(step)\n",
    "        fig.add_trace(go.Bar(\n",
    "            visible=False,\n",
    "            y=countries['country_txt'],\n",
    "            x=countries['organized'],\n",
    "            name='Organized',\n",
    "            orientation='h',\n",
    "            marker=dict(\n",
    "                color='rgba(246, 78, 139, 0.6)',\n",
    "                line=dict(color='rgba(246, 78, 139, 1.0)', width=3)\n",
    "            )\n",
    "        ))\n",
    "        fig.add_trace(go.Bar(\n",
    "            visible=False,\n",
    "            y=countries['country_txt'],\n",
    "            x=countries['unorganized'],\n",
    "            name='Unorganized',\n",
    "            orientation='h',\n",
    "            marker=dict(\n",
    "                color='#5885AF',\n",
    "                opacity = 0.8,\n",
    "                line=dict(color='rgba(58, 71, 80, 1.0)', width=3)\n",
    "            )\n",
    "        ))\n",
    "\n",
    "    fig.data[-1].visible = True\n",
    "    fig.data[-2].visible = True\n",
    "\n",
    "    steps = []\n",
    "    for i in range(len(years)):\n",
    "        step = dict(\n",
    "            method=\"update\",\n",
    "            args=[{\"visible\": [False] * len(fig.data)},],  # layout attribute\n",
    "        )\n",
    "        step[\"args\"][0][\"visible\"][i * 2] = True  # Toggle i'th trace to \"visible\"\n",
    "        if i * 2 < len(fig.data) - 1:\n",
    "            step[\"args\"][0][\"visible\"][i * 2 + 1] = True  # Toggle i'th trace to \"visible\"\n",
    "        steps.append(step)\n",
    "\n",
    "    sliders = [dict(\n",
    "        active=48,\n",
    "        currentvalue={\"prefix\": \"Selected Year: \"},\n",
    "        pad={\"t\": 50},\n",
    "        steps=steps\n",
    "    )]\n",
    "\n",
    "    fig.update_layout(\n",
    "        sliders=sliders,\n",
    "        barmode='stack'\n",
    "    )\n",
    "\n",
    "    fig['layout']['sliders'][0]['currentvalue']['prefix']='Year: '\n",
    "    for i, date in enumerate(years, start = 0):\n",
    "        fig['layout']['sliders'][0]['steps'][i]['label']=str(date)\n",
    "        \n",
    "#     fig.update_layout(margin=dict(t=120))\n",
    "    fig['layout']['sliders'][0]['pad']=dict(t= -360,)\n",
    "    \n",
    "    return fig\n",
    "        \n",
    "\n",
    "\n",
    "\n",
    "@app.callback(\n",
    "    [dash.dependencies.Output('incidents', 'figure'), dash.dependencies.Output('incident-box', 'style')],\n",
    "    [dash.dependencies.Input('world-map', 'clickData')])\n",
    "def update_incidents(clickData):\n",
    "    df_agg = ''\n",
    "    if clickData is not None:\n",
    "        selected_country =clickData['points'][0]['location']\n",
    "        df_agg = df_merged[df_merged['id'] == selected_country].groupby(by=['iyear','country',\n",
    "                                                                            'country_txt','id', \n",
    "                                                                            'isOrganized']).agg({\n",
    "                                                                                        'eventid':'count'}).reset_index()\n",
    "    fig = px.line(df_agg, x=\"iyear\", y=\"eventid\", color='isOrganized',\n",
    "                  labels={\n",
    "                     \"iyear\": \"<b>Year</b>\",\n",
    "                     \"eventid\": \"<b>Number of Incidents</b>\",\n",
    "                     \"isOrganized\": \" \"\n",
    "                 }, title=\"<b>Number of Incidents by Years</b>\")\n",
    "    \n",
    "    return fig,  {'visibility':'visible'}\n",
    "\n",
    "@app.callback(\n",
    "    [dash.dependencies.Output('fatalities', 'figure'), dash.dependencies.Output('fatalities-box', 'style')],\n",
    "    [dash.dependencies.Input('world-map', 'clickData')])\n",
    "def update_fatalities(clickData):\n",
    "    df_agg = ''\n",
    "    \n",
    "    fig = make_subplots(specs=[[{\"secondary_y\": True}]])\n",
    "\n",
    "    if clickData is not None:\n",
    "        selected_country =clickData['points'][0]['location']\n",
    "        df_agg = df_merged[df_merged['id'] == selected_country].groupby(by=['iyear','country',\n",
    "                                                                        'country_txt','id']).agg({\n",
    "                                                                                        'nkill':np.sum,\n",
    "                                                                                        'nwound':np.sum  }).reset_index()\n",
    "    # Add traces\n",
    "    fig.add_trace(\n",
    "        go.Line(x=df_agg['iyear'], y=df_agg['nwound'], name=\"Injuries\", line=dict(color=\"#D4AC0D\")),\n",
    "        secondary_y=False,\n",
    "    )\n",
    "\n",
    "    fig.add_trace(\n",
    "        go.Line(x=df_agg['iyear'], y=df_agg['nkill'], name=\"Fatalities\", line=dict(color=\"#943126\")),\n",
    "        secondary_y=True,\n",
    "    )     \n",
    "    \n",
    "    # Add figure title\n",
    "    fig.update_layout(\n",
    "        title_text=\"<b>Number of Injuries and Fatalities by Years</b>\"\n",
    "    )\n",
    "\n",
    "    # Set x-axis title\n",
    "    fig.update_xaxes(title_text=\"<b>Year</b>\")\n",
    "\n",
    "    # Set y-axes titles\n",
    "    fig.update_yaxes(title_text=\"<b>Injuries</b>\", secondary_y=False)\n",
    "    fig.update_yaxes(title_text=\"<b>Fatalities</b> \", secondary_y=True)\n",
    "\n",
    "    \n",
    "    return fig, {'visibility':'visible'}\n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9ea21584",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.8"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
